version: '3.3'

# This is a mirror of the normal docker-compose but with a build-in-built.
# Beware: For the Java Sources you still need to do the maven goals locally first!

services:
  obfuscator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OBFUSCATOR_VERSION: 1.1-SNAPSHOT
    image: lampion/java-obfuscator:latest
    volumes:
      - ./compose_output:/app/obfuscator_output
      - ./src/test/resources/javafiles_perMethodEach:/app/obfuscator_input
