name: Python CI on PR - Python Transformer

on: 
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  pull_request:
    paths:
      - 'Transformers/Python/*'
    branches:
      - main 
  push:
    paths:
      - 'Transformers/Python/*'
    branches:
      - main

jobs:

  buildWithPythonWheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Python deps
      working-directory: ./Transformers/Python
      run: |
        pip install pytest libcst build 
    - name: Build Python Transformer
      working-directory: ./Transformers/Python
      run: |
        python3 -m build --wheel
    - name: Test Python Transformer
      working-directory: ./Transformers/Python
      run: |
        python3 -m pytest ./tests

  buildWithDocker: 
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/ciselab/lampion/python
            lampion/python
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Transformers/Python
          build-args: |
            "PYTHON_VERSION=3.9.7"
            "LAMPION_VERSION=0.0.1"
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
