name: Java CI on PR - Java Obfuscator

on: 
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  pull_request:
    branches: 
      - master
      - dev

jobs:
  buildWithMaven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build Java Obfuscator
      run: mvn package verify
