name: Java CI on PR - Java Transformer

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Transformers/Java/**'
  push:
    branches:
      - main
    paths:
      - 'Transformers/Java/**'

jobs:
  buildWithMaven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build Java Transformer
      run: mvn package verify -P nofiles --file Transformers/Java/pom.xml


  buildWithDocker: 
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/ciselab/lampion/java-transformer
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Transformers/Java
          build-args: |
            "TRANSFORMER_VERSION=1.4-SNAPSHOT"
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
