name: Java CI on PR - Java Obfuscator

on: 
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  pull_request:
    paths:
      - 'JavaObfuscator/*'

jobs:
  buildWithMaven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build Java Obfuscator
      run: mvn package verify --file JavaObfuscator/pom.xml -Pnofiles
