name: Java CI on PR - Java Transformer

on: 
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  pull_request:
    paths:
      - 'Transformers/Java/*'
    branches:
      - main 
  push:
    paths:
      - 'Transformers/Java/*'
    branches:
      - main

jobs:
  buildWithMaven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build Java Transformer
      run: mvn package verify --file Transformers/Java/pom.xml
