name: Automatic Dependabot Merge

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
        
  merge-me:
    name: Dependabot merge
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 180 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '210s'

      - name: Dependabot merge
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
